CRITICAL - 2025-08-12 14:10:05 --> TypeError: CodeIgniter\Database\BaseBuilder::getOperatorFromWhereKey(): Argument #1 ($whereKey) must be of type string, int given, called in C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseBuilder.php on line 781
[Method: GET, Route: buscar_marca/26]
in SYSTEMPATH\Database\BaseBuilder.php on line 3495.
 1 SYSTEMPATH\Database\BaseBuilder.php(781): CodeIgniter\Database\BaseBuilder->getOperatorFromWhereKey(0)
 2 SYSTEMPATH\Database\BaseBuilder.php(722): CodeIgniter\Database\BaseBuilder->whereHaving('QBWhere', [...], null, 'AND ', true)
 3 SYSTEMPATH\Model.php(925): CodeIgniter\Database\BaseBuilder->where([...])
 4 APPPATH\Controllers\MarcaController.php(36): CodeIgniter\Model->__call('where', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MarcaController->buscar('26')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MarcaController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-12 14:10:08 --> TypeError: CodeIgniter\Database\BaseBuilder::getOperatorFromWhereKey(): Argument #1 ($whereKey) must be of type string, int given, called in C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseBuilder.php on line 781
[Method: GET, Route: buscar_marca/26]
in SYSTEMPATH\Database\BaseBuilder.php on line 3495.
 1 SYSTEMPATH\Database\BaseBuilder.php(781): CodeIgniter\Database\BaseBuilder->getOperatorFromWhereKey(0)
 2 SYSTEMPATH\Database\BaseBuilder.php(722): CodeIgniter\Database\BaseBuilder->whereHaving('QBWhere', [...], null, 'AND ', true)
 3 SYSTEMPATH\Model.php(925): CodeIgniter\Database\BaseBuilder->where([...])
 4 APPPATH\Controllers\MarcaController.php(36): CodeIgniter\Model->__call('where', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MarcaController->buscar('26')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MarcaController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-12 14:11:42 --> ParseError: syntax error, unexpected token "=", expecting "]"
[Method: GET, Route: buscar_marca/26]
in APPPATH\Controllers\MarcaController.php on line 36.
 1 SYSTEMPATH\Autoloader\Autoloader.php(295): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\fs2025\\repaso0408\\repaso\\app\\Controllers\\MarcaController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(271): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\MarcaController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\MarcaController')
 4 SYSTEMPATH\CodeIgniter.php(885): class_exists('\\App\\Controllers\\MarcaController', true)
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-12 14:11:43 --> ParseError: syntax error, unexpected token "=", expecting "]"
[Method: GET, Route: buscar_marca/26]
in APPPATH\Controllers\MarcaController.php on line 36.
 1 SYSTEMPATH\Autoloader\Autoloader.php(295): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\fs2025\\repaso0408\\repaso\\app\\Controllers\\MarcaController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(271): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\MarcaController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\MarcaController')
 4 SYSTEMPATH\CodeIgniter.php(885): class_exists('\\App\\Controllers\\MarcaController', true)
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-12 14:12:07 --> CodeIgniter\Database\Exceptions\DatabaseException: Updates are not allowed unless they contain a "where" or "like" clause.
[Method: POST, Route: editar_marca]
in SYSTEMPATH\Model.php on line 456.
 1 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate(null, [...])
 2 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update(null, [...])
 3 APPPATH\Controllers\EmpleadoController.php(59): CodeIgniter\Model->update(null, [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->editar()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-12 15:27:42 --> mysqli_sql_exception: Unknown column 'puestos_id' in 'field list' in C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `pu...', 0)
#1 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pu...')
#2 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pu...')
#3 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pu...', Array, false)
#4 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\fs2025\repaso0408\repaso\app\Controllers\PuestoController.php(23): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(933): App\Controllers\PuestoController->agregar()
#9 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PuestoController))
#10 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2025\repaso0408\repaso\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-08-12 15:27:42 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'puestos_id' in 'field list'
[Method: POST, Route: agregarPuesto]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `puestos` (`puestos_id`, `puesto`) VALUES (:puestos_id:, :puesto:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\PuestoController.php(23): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PuestoController->agregar()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PuestoController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-12 15:27:42 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'puestos_id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `puestos` (`puestos_id`, `puesto`) VALUES (\'16\', \'EJEMPLO\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `puestos` (`puestos_id`, `puesto`) VALUES (\'16\', \'EJEMPLO\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `puestos` (`puestos_id`, `puesto`) VALUES (:puestos_id:, :puesto:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\PuestoController.php(23): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PuestoController->agregar()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PuestoController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-12 15:27:42 --> [Caused by] mysqli_sql_exception: Unknown column 'puestos_id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `puestos` (`puestos_id`, `puesto`) VALUES (\'16\', \'EJEMPLO\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `puestos` (`puestos_id`, `puesto`) VALUES (\'16\', \'EJEMPLO\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `puestos` (`puestos_id`, `puesto`) VALUES (\'16\', \'EJEMPLO\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `puestos` (`puestos_id`, `puesto`) VALUES (:puestos_id:, :puesto:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\PuestoController.php(23): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PuestoController->agregar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PuestoController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-12 15:31:52 --> mysqli_sql_exception: Unknown column 'puestos_id' in 'where clause' in C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php(327): mysqli->query('DELETE FROM `pu...', 0)
#1 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `pu...')
#2 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `pu...')
#3 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseBuilder.php(2848): CodeIgniter\Database\BaseConnection->query('DELETE FROM `pu...', Array, false)
#4 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\BaseModel.php(1152): CodeIgniter\Model->doDelete(Array, false)
#6 C:\xampp\htdocs\fs2025\repaso0408\repaso\app\Controllers\PuestoController.php(30): CodeIgniter\BaseModel->delete(Array)
#7 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(933): App\Controllers\PuestoController->eliminar('16')
#8 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PuestoController))
#9 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\fs2025\repaso0408\repaso\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-08-12 15:31:52 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'puestos_id' in 'where clause'
[Method: GET, Route: eliminar_puesto/16]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2848): CodeIgniter\Database\BaseConnection->query('DELETE FROM `puestos`
WHERE `puestos_id` IN :puestos_id:', [...], false)
 2 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 3 SYSTEMPATH\BaseModel.php(1152): CodeIgniter\Model->doDelete([...], false)
 4 APPPATH\Controllers\PuestoController.php(30): CodeIgniter\BaseModel->delete([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PuestoController->eliminar('16')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PuestoController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-12 15:31:52 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'puestos_id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `puestos`
WHERE `puestos_id` IN (\'16\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `puestos`
WHERE `puestos_id` IN (\'16\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2848): CodeIgniter\Database\BaseConnection->query('DELETE FROM `puestos`
WHERE `puestos_id` IN :puestos_id:', [...], false)
 4 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 5 SYSTEMPATH\BaseModel.php(1152): CodeIgniter\Model->doDelete([...], false)
 6 APPPATH\Controllers\PuestoController.php(30): CodeIgniter\BaseModel->delete([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PuestoController->eliminar('16')
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PuestoController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-12 15:31:52 --> [Caused by] mysqli_sql_exception: Unknown column 'puestos_id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('DELETE FROM `puestos`
WHERE `puestos_id` IN (\'16\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `puestos`
WHERE `puestos_id` IN (\'16\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `puestos`
WHERE `puestos_id` IN (\'16\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2848): CodeIgniter\Database\BaseConnection->query('DELETE FROM `puestos`
WHERE `puestos_id` IN :puestos_id:', [...], false)
 5 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 6 SYSTEMPATH\BaseModel.php(1152): CodeIgniter\Model->doDelete([...], false)
 7 APPPATH\Controllers\PuestoController.php(30): CodeIgniter\BaseModel->delete([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PuestoController->eliminar('16')
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PuestoController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-12 15:32:21 --> mysqli_sql_exception: Unknown column 'puestos_id' in 'where clause' in C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php(327): mysqli->query('DELETE FROM `pu...', 0)
#1 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `pu...')
#2 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `pu...')
#3 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseBuilder.php(2848): CodeIgniter\Database\BaseConnection->query('DELETE FROM `pu...', Array, false)
#4 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\BaseModel.php(1152): CodeIgniter\Model->doDelete(Array, false)
#6 C:\xampp\htdocs\fs2025\repaso0408\repaso\app\Controllers\PuestoController.php(30): CodeIgniter\BaseModel->delete(Array)
#7 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(933): App\Controllers\PuestoController->eliminar('16')
#8 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PuestoController))
#9 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\fs2025\repaso0408\repaso\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-08-12 15:32:21 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'puestos_id' in 'where clause'
[Method: GET, Route: eliminar_puesto/16]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2848): CodeIgniter\Database\BaseConnection->query('DELETE FROM `puestos`
WHERE `puestos_id` IN :puestos_id:', [...], false)
 2 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 3 SYSTEMPATH\BaseModel.php(1152): CodeIgniter\Model->doDelete([...], false)
 4 APPPATH\Controllers\PuestoController.php(30): CodeIgniter\BaseModel->delete([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PuestoController->eliminar('16')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PuestoController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-12 15:32:21 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'puestos_id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `puestos`
WHERE `puestos_id` IN (\'16\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `puestos`
WHERE `puestos_id` IN (\'16\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2848): CodeIgniter\Database\BaseConnection->query('DELETE FROM `puestos`
WHERE `puestos_id` IN :puestos_id:', [...], false)
 4 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 5 SYSTEMPATH\BaseModel.php(1152): CodeIgniter\Model->doDelete([...], false)
 6 APPPATH\Controllers\PuestoController.php(30): CodeIgniter\BaseModel->delete([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PuestoController->eliminar('16')
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PuestoController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-12 15:32:21 --> [Caused by] mysqli_sql_exception: Unknown column 'puestos_id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('DELETE FROM `puestos`
WHERE `puestos_id` IN (\'16\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `puestos`
WHERE `puestos_id` IN (\'16\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `puestos`
WHERE `puestos_id` IN (\'16\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2848): CodeIgniter\Database\BaseConnection->query('DELETE FROM `puestos`
WHERE `puestos_id` IN :puestos_id:', [...], false)
 5 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 6 SYSTEMPATH\BaseModel.php(1152): CodeIgniter\Model->doDelete([...], false)
 7 APPPATH\Controllers\PuestoController.php(30): CodeIgniter\BaseModel->delete([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PuestoController->eliminar('16')
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PuestoController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-12 15:32:21 --> mysqli_sql_exception: Unknown column 'puestos_id' in 'where clause' in C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php(327): mysqli->query('DELETE FROM `pu...', 0)
#1 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `pu...')
#2 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `pu...')
#3 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseBuilder.php(2848): CodeIgniter\Database\BaseConnection->query('DELETE FROM `pu...', Array, false)
#4 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\BaseModel.php(1152): CodeIgniter\Model->doDelete(Array, false)
#6 C:\xampp\htdocs\fs2025\repaso0408\repaso\app\Controllers\PuestoController.php(30): CodeIgniter\BaseModel->delete(Array)
#7 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(933): App\Controllers\PuestoController->eliminar('16')
#8 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PuestoController))
#9 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\fs2025\repaso0408\repaso\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-08-12 15:32:21 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'puestos_id' in 'where clause'
[Method: GET, Route: eliminar_puesto/16]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2848): CodeIgniter\Database\BaseConnection->query('DELETE FROM `puestos`
WHERE `puestos_id` IN :puestos_id:', [...], false)
 2 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 3 SYSTEMPATH\BaseModel.php(1152): CodeIgniter\Model->doDelete([...], false)
 4 APPPATH\Controllers\PuestoController.php(30): CodeIgniter\BaseModel->delete([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PuestoController->eliminar('16')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PuestoController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-12 15:32:21 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'puestos_id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `puestos`
WHERE `puestos_id` IN (\'16\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `puestos`
WHERE `puestos_id` IN (\'16\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2848): CodeIgniter\Database\BaseConnection->query('DELETE FROM `puestos`
WHERE `puestos_id` IN :puestos_id:', [...], false)
 4 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 5 SYSTEMPATH\BaseModel.php(1152): CodeIgniter\Model->doDelete([...], false)
 6 APPPATH\Controllers\PuestoController.php(30): CodeIgniter\BaseModel->delete([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PuestoController->eliminar('16')
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PuestoController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-12 15:32:21 --> [Caused by] mysqli_sql_exception: Unknown column 'puestos_id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('DELETE FROM `puestos`
WHERE `puestos_id` IN (\'16\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `puestos`
WHERE `puestos_id` IN (\'16\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `puestos`
WHERE `puestos_id` IN (\'16\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2848): CodeIgniter\Database\BaseConnection->query('DELETE FROM `puestos`
WHERE `puestos_id` IN :puestos_id:', [...], false)
 5 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 6 SYSTEMPATH\BaseModel.php(1152): CodeIgniter\Model->doDelete([...], false)
 7 APPPATH\Controllers\PuestoController.php(30): CodeIgniter\BaseModel->delete([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PuestoController->eliminar('16')
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PuestoController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-12 15:32:21 --> mysqli_sql_exception: Unknown column 'puestos_id' in 'where clause' in C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php(327): mysqli->query('DELETE FROM `pu...', 0)
#1 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `pu...')
#2 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `pu...')
#3 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseBuilder.php(2848): CodeIgniter\Database\BaseConnection->query('DELETE FROM `pu...', Array, false)
#4 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\BaseModel.php(1152): CodeIgniter\Model->doDelete(Array, false)
#6 C:\xampp\htdocs\fs2025\repaso0408\repaso\app\Controllers\PuestoController.php(30): CodeIgniter\BaseModel->delete(Array)
#7 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(933): App\Controllers\PuestoController->eliminar('16')
#8 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PuestoController))
#9 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\fs2025\repaso0408\repaso\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-08-12 15:32:21 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'puestos_id' in 'where clause'
[Method: GET, Route: eliminar_puesto/16]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2848): CodeIgniter\Database\BaseConnection->query('DELETE FROM `puestos`
WHERE `puestos_id` IN :puestos_id:', [...], false)
 2 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 3 SYSTEMPATH\BaseModel.php(1152): CodeIgniter\Model->doDelete([...], false)
 4 APPPATH\Controllers\PuestoController.php(30): CodeIgniter\BaseModel->delete([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PuestoController->eliminar('16')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PuestoController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-12 15:32:21 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'puestos_id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `puestos`
WHERE `puestos_id` IN (\'16\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `puestos`
WHERE `puestos_id` IN (\'16\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2848): CodeIgniter\Database\BaseConnection->query('DELETE FROM `puestos`
WHERE `puestos_id` IN :puestos_id:', [...], false)
 4 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 5 SYSTEMPATH\BaseModel.php(1152): CodeIgniter\Model->doDelete([...], false)
 6 APPPATH\Controllers\PuestoController.php(30): CodeIgniter\BaseModel->delete([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PuestoController->eliminar('16')
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PuestoController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-12 15:32:21 --> [Caused by] mysqli_sql_exception: Unknown column 'puestos_id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('DELETE FROM `puestos`
WHERE `puestos_id` IN (\'16\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `puestos`
WHERE `puestos_id` IN (\'16\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `puestos`
WHERE `puestos_id` IN (\'16\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2848): CodeIgniter\Database\BaseConnection->query('DELETE FROM `puestos`
WHERE `puestos_id` IN :puestos_id:', [...], false)
 5 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 6 SYSTEMPATH\BaseModel.php(1152): CodeIgniter\Model->doDelete([...], false)
 7 APPPATH\Controllers\PuestoController.php(30): CodeIgniter\BaseModel->delete([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PuestoController->eliminar('16')
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PuestoController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-12 15:32:34 --> mysqli_sql_exception: Unknown column 'puestos_id' in 'where clause' in C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php(327): mysqli->query('DELETE FROM `pu...', 0)
#1 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `pu...')
#2 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `pu...')
#3 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseBuilder.php(2848): CodeIgniter\Database\BaseConnection->query('DELETE FROM `pu...', Array, false)
#4 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\BaseModel.php(1152): CodeIgniter\Model->doDelete(Array, false)
#6 C:\xampp\htdocs\fs2025\repaso0408\repaso\app\Controllers\PuestoController.php(30): CodeIgniter\BaseModel->delete(Array)
#7 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(933): App\Controllers\PuestoController->eliminar('16')
#8 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PuestoController))
#9 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\fs2025\repaso0408\repaso\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-08-12 15:32:34 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'puestos_id' in 'where clause'
[Method: GET, Route: eliminar_puesto/16]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2848): CodeIgniter\Database\BaseConnection->query('DELETE FROM `puestos`
WHERE `puestos_id` IN :puestos_id:', [...], false)
 2 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 3 SYSTEMPATH\BaseModel.php(1152): CodeIgniter\Model->doDelete([...], false)
 4 APPPATH\Controllers\PuestoController.php(30): CodeIgniter\BaseModel->delete([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PuestoController->eliminar('16')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PuestoController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-12 15:32:34 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'puestos_id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `puestos`
WHERE `puestos_id` IN (\'16\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `puestos`
WHERE `puestos_id` IN (\'16\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2848): CodeIgniter\Database\BaseConnection->query('DELETE FROM `puestos`
WHERE `puestos_id` IN :puestos_id:', [...], false)
 4 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 5 SYSTEMPATH\BaseModel.php(1152): CodeIgniter\Model->doDelete([...], false)
 6 APPPATH\Controllers\PuestoController.php(30): CodeIgniter\BaseModel->delete([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PuestoController->eliminar('16')
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PuestoController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-12 15:32:34 --> [Caused by] mysqli_sql_exception: Unknown column 'puestos_id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('DELETE FROM `puestos`
WHERE `puestos_id` IN (\'16\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `puestos`
WHERE `puestos_id` IN (\'16\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `puestos`
WHERE `puestos_id` IN (\'16\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2848): CodeIgniter\Database\BaseConnection->query('DELETE FROM `puestos`
WHERE `puestos_id` IN :puestos_id:', [...], false)
 5 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 6 SYSTEMPATH\BaseModel.php(1152): CodeIgniter\Model->doDelete([...], false)
 7 APPPATH\Controllers\PuestoController.php(30): CodeIgniter\BaseModel->delete([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PuestoController->eliminar('16')
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PuestoController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-12 15:36:42 --> ErrorException: Undefined array key "equipo_id"
[Method: GET, Route: buscar_puesto/16]
in APPPATH\Views\form_modificar_puestos.php on line 18.
 1 APPPATH\Views\form_modificar_puestos.php(18): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "equipo_id"', 'C:\\xampp\\htdocs\\fs2025\\repaso0408\\repaso\\app\\Views\\form_modificar_puestos.php', 18)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\fs2025\\repaso0408\\repaso\\app\\Views\\form_modificar_puestos.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('form_modificar_puestos', [], true)
 5 APPPATH\Controllers\PuestoController.php(38): view('form_modificar_puestos', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PuestoController->buscar('16')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PuestoController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-12 15:39:21 --> ErrorException: Undefined array key "equipo_id"
[Method: GET, Route: buscar_puesto/15]
in APPPATH\Views\form_modificar_puestos.php on line 18.
 1 APPPATH\Views\form_modificar_puestos.php(18): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "equipo_id"', 'C:\\xampp\\htdocs\\fs2025\\repaso0408\\repaso\\app\\Views\\form_modificar_puestos.php', 18)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\fs2025\\repaso0408\\repaso\\app\\Views\\form_modificar_puestos.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('form_modificar_puestos', [], true)
 5 APPPATH\Controllers\PuestoController.php(38): view('form_modificar_puestos', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PuestoController->buscar('15')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PuestoController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-12 16:45:21 --> mysqli_sql_exception: Duplicate entry '52' for key 'PRIMARY' in C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `ro...', 0)
#1 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ro...')
#2 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ro...')
#3 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ro...', Array, false)
#4 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\fs2025\repaso0408\repaso\app\Controllers\RolController.php(24): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(933): App\Controllers\RolController->agregar()
#9 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RolController))
#10 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2025\repaso0408\repaso\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-08-12 16:45:21 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '52' for key 'PRIMARY'
[Method: POST, Route: agregarRol]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `roles` (`rol_id`, `nombre`, `descripcion`) VALUES (:rol_id:, :nombre:, :descripcion:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\RolController.php(24): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\RolController->agregar()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RolController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-12 16:45:21 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '52' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `roles` (`rol_id`, `nombre`, `descripcion`) VALUES (\'52\', \'ROL DE PRUEBA \', \'PRUEBA 123\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `roles` (`rol_id`, `nombre`, `descripcion`) VALUES (\'52\', \'ROL DE PRUEBA \', \'PRUEBA 123\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `roles` (`rol_id`, `nombre`, `descripcion`) VALUES (:rol_id:, :nombre:, :descripcion:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\RolController.php(24): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\RolController->agregar()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RolController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-12 16:45:21 --> [Caused by] mysqli_sql_exception: Duplicate entry '52' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `roles` (`rol_id`, `nombre`, `descripcion`) VALUES (\'52\', \'ROL DE PRUEBA \', \'PRUEBA 123\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `roles` (`rol_id`, `nombre`, `descripcion`) VALUES (\'52\', \'ROL DE PRUEBA \', \'PRUEBA 123\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `roles` (`rol_id`, `nombre`, `descripcion`) VALUES (\'52\', \'ROL DE PRUEBA \', \'PRUEBA 123\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `roles` (`rol_id`, `nombre`, `descripcion`) VALUES (:rol_id:, :nombre:, :descripcion:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\RolController.php(24): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\RolController->agregar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RolController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-12 17:15:28 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: POST, Route: editar_rol]
in SYSTEMPATH\BaseModel.php on line 1823.
 1 SYSTEMPATH\BaseModel.php(1823): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(994): CodeIgniter\BaseModel->transformDataToArray(null, 'update')
 3 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update(null, null)
 4 APPPATH\Controllers\RolController.php(52): CodeIgniter\Model->update()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\RolController->editar()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RolController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
